---
title: "Data Prep Additional Step for Modeling Each Variable"
author: "Steven Futter"
date: "5/1/2017"
output: html_document
---

```{r}
library(dplyr)
# inPath = file.path("~/Dropbox","NU","THESIS","DATASETS","GROOMED") # Home path
# df = read.csv(file.path(inPath,"greenwich_eltham_imputed_school_hours.csv"),na.strings=c("NA"," "))

processPart1 = function(df){
  df = df[,2:length(names(df))] 
  df$Date         = as.Date(df$Date, '%Y-%m-%d')
  df$Year         = as.factor(df$Year)
  df$Month        = as.factor(df$Month)
  df$Week         = as.factor(df$Week)
  df$Day          = as.factor(df$Day)
  df$TimeHoursNum = as.factor(df$TimeHoursNum)
  return(df)
}



# Remove column X that has been added


# make sure that the non-numeric columns are set up correctly
df$Date         = as.Date(df$Date, '%Y-%m-%d')
df$Year         = as.factor(df$Year)
df$Month        = as.factor(df$Month)
df$Week         = as.factor(df$Week)
df$Day          = as.factor(df$Day)
df$TimeHoursNum = as.factor(df$TimeHoursNum)

names(df)

```


```{r}
dropCols = which(names(df) %in% c('Date','Week')) # remove Week as overlap with the month column.       #,'NO','NOX','O3','PM10','PM2.5','TimeHoursNum','Date','Year','Month','Week','Day'))
df = df[,-dropCols]
names(df)
str(df)

# Reposition the data in the dataframe so that the predictor is in the left-most column. Easier to read and this fits into the code below for h2o ann
df <- df %>% select(NO2, everything())

############################################################################################################################################################
# QUESTION: DO WE INCLUDE THE LAGGED VALUES OR NOT? SERIAL CORRELATION RISK. I SUGGEST WE DO NOT INCLUDE THE LAGS THEN DO A WRITE-UP TALKING ABOUT WHY NOT.
names(df)
dim(df)
#df <- df %>% select(NO2, Year:WSPD)
df <- df %>% filter(TimeHoursNum=='9') %>% select(NO2, lag.1.NO:lag.3.WSPD)
dim(df)

############################################################################################################################################################

# Prep the testing data using 70-30 split
smp.size = floor(0.70 * nrow(df))
set.seed(123)
train = sample(seq_len(nrow(df)), size = smp.size)
test = -train

df.train = df[train,]
df.test  = df[-train,]

dim(df.train)  # 336  54 -> 40    -> 2001 X 18
dim(df.test)   # 144  54 -> 40    -> 859  X 18
```


